version: "3"
services:
  nginx:
    ports:
      - "${PORT}:80"
    volumes:
      - ./nginx/prod.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app

  node-app:
    build:
      context: .
      args:
        NODE_ENV: ${NODE_ENV}
        MONGO_USER: ${MONGO_USER}
        MONGO_PASSWORD: ${MONGO_PASSWORD}
    env_file:
      - ./.env.production.local
    command: npm run prod
    depends_on:
      - mongo

  mongo:
    container_name: prod_mongo
    ports:
      - "${MONGO_DB_PORT}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_PROD_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_PROD_ROOT_PASSWORD}
    volumes:
      - mongo-data-prod:/data/db

volumes:
  mongo-data-prod: