version: "3"
services:
  nginx:
    ports:
      - "${PORT}:80"
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app
  node-app:
    build:
      context: .
      args:
        NODE_ENV: ${NODE_ENV}
        MONGO_USER: ${MONGO_USER}
        MONGO_PASSWORD: ${MONGO_PASSWORD}
    image: alierensh3/hangcoffee-dev
    volumes:
      - ./:/app:ro
      - /app/node_modules
    env_file:
      - ./.env.development.local
    command: npm run dev
    depends_on:
      - mongo
  mongo:
    container_name: dev_mongo
    ports:
      - "${MONGO_DB_PORT}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_DEV_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_DEV_ROOT_PASSWORD}
    volumes:
      - mongo-data-dev:/data/db
      
volumes:
  mongo-data-dev: